### ISSUE TITLE
Legend?

### ISSUE THREAD

**Issue by ff6347** [vogelino/periodic-table-data-visualization#1]
Looks awesome. Just one thing. A legend is missing. What's the number in the circle? What's the acronym behind the number? I can guess but it is not clear

**Comment by ff6347** [comment]
Also needs a axis on x what is it? Again I can guess but guessing is not knowing.

**Comment by vogelino** [comment]
Sure sure! I'm not finished! :smiley: I planed to integrate a legend and an x axis. I'm just not as far for now. It will be finished tonight.

**Comment by ff6347** [comment]
Aight.
